//
//  TemplateViewController.swift
//  eMia
//
//  Created Sergey Krotkih on 04/09/2018.
//  Copyright © 2018 Sergey Krotkih. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TemplateViewController: UIViewController, TemplateViewProtocol {

	var presenter: TemplatePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
