//
//  TemplateRouter.swift
//  eMia
//
//  Created Сергей Кротких on 04/09/2018.
//  Copyright © 2018 Coded I/S. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TemplateRouter: TemplateWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = TemplateViewController(nibName: nil, bundle: nil)
        let interactor = TemplateInteractor()
        let router = TemplateRouter()
        let presenter = TemplatePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
