//
//  TemplatePresenter.swift
//  eMia
//
//  Created Сергей Кротких on 04/09/2018.
//  Copyright © 2018 Coded I/S. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TemplatePresenter: TemplatePresenterProtocol, TemplateInteractorOutputProtocol {

    weak private var view: TemplateViewProtocol?
    var interactor: TemplateInteractorInputProtocol?
    private let router: TemplateWireframeProtocol

    init(interface: TemplateViewProtocol, interactor: TemplateInteractorInputProtocol?, router: TemplateWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
